#!/usr/bin/env bash
set -euo pipefail

# Build the network-free Zephyr periodic latency sampler at the RT partition's
# identity-mapped guest address and stage a raw image plus reproducibility data.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
source "$repo_root/scripts/lib/task123-tools.sh"
zephyr_revision="dccb09599635bdff17633fa7e9dab014b91dce90"
zephyr_base="${ZEPHYR_BASE:-$repo_root/.deps/task123/zephyr-$zephyr_revision}"
zephyr_source_revision="${ZEPHYR_SOURCE_REVISION:-}"
task123_python="$(resolve_task123_python "$repo_root" "$zephyr_revision")"
cross_prefix="$(resolve_task123_cross_prefix)"
app_dir="${repo_root}/scripts/test/zephyr-periodic"
out_dir="${OUT_DIR:-${repo_root}/tmp/rt-partition}"
build_dir="${BUILD_DIR:-${out_dir}/zephyr-periodic-build}"
zephyr_board="${ZEPHYR_BOARD:-qemu_cortex_a53}"
memory_base="${ZEPHYR_MEMORY_BASE:-0xA0000000}"
memory_size="${ZEPHYR_MEMORY_SIZE:-0x08000000}"
memory_address_cells="${ZEPHYR_MEMORY_ADDRESS_CELLS:-2}"
start_gated="${ZEPHYR_START_GATED:-1}"
dump_gated="${ZEPHYR_DUMP_GATED:-0}"
dump_chunk_rows="${ZEPHYR_DUMP_CHUNK_ROWS:-256}"
start_delay_ms="${ZEPHYR_START_DELAY_MS:-0}"
sample_count="${ZEPHYR_SAMPLE_COUNT:-300}"
extra_overlay="${ZEPHYR_EXTRA_OVERLAY:-}"
extra_conf="${ZEPHYR_EXTRA_CONF:-}"
atk_early_uart="${ZEPHYR_ATK_EARLY_UART:-0}"
out_dir="$(realpath -m "$out_dir")"
build_dir="$(realpath -m "$build_dir")"

for path in "$zephyr_base" "$app_dir" "${cross_prefix}gcc"; do
    [[ -e "$path" ]] || { printf 'error: missing Zephyr build input: %s\n' "$path" >&2; exit 1; }
done
command -v dtc >/dev/null 2>&1 || {
    printf 'error: required executable is unavailable: dtc\n' >&2
    exit 1
}
if [[ -z "$zephyr_source_revision" ]]; then
    zephyr_source_revision="$(task123_source_revision "$zephyr_base" 2>/dev/null || true)"
fi
[[ "$zephyr_source_revision" == "$zephyr_revision" ]] || {
    printf 'error: Zephyr source revision must be %s, got %s\n' \
        "$zephyr_revision" "${zephyr_source_revision:-unknown}" >&2
    exit 1
}
task123_source_is_pristine "$zephyr_base" || {
    printf 'error: refusing to build from a modified Zephyr source; use a clean ZEPHYR_BASE\n' >&2
    exit 1
}
task123_check_zephyr_python "$task123_python"
[[ "$memory_base" =~ ^0x[0-9a-fA-F]+$ && "$memory_size" =~ ^0x[0-9a-fA-F]+$ ]] || {
    printf 'error: Zephyr memory base and size must be hexadecimal\n' >&2
    exit 2
}
[[ "$zephyr_board" =~ ^[A-Za-z0-9_./-]+$ ]] || {
    printf 'error: ZEPHYR_BOARD contains unsupported characters: %s\n' "$zephyr_board" >&2
    exit 2
}
[[ "$memory_address_cells" == "1" || "$memory_address_cells" == "2" ]] || {
    printf 'error: ZEPHYR_MEMORY_ADDRESS_CELLS must be 1 or 2\n' >&2
    exit 2
}
[[ "$start_gated" == "0" || "$start_gated" == "1" ]] || {
    printf 'error: ZEPHYR_START_GATED must be 0 or 1\n' >&2
    exit 2
}
[[ "$dump_gated" == "0" || "$dump_gated" == "1" ]] || {
    printf 'error: ZEPHYR_DUMP_GATED must be 0 or 1\n' >&2
    exit 2
}
[[ "$dump_chunk_rows" =~ ^[1-9][0-9]*$ ]] || {
    printf 'error: ZEPHYR_DUMP_CHUNK_ROWS must be a positive integer\n' >&2
    exit 2
}
[[ "$dump_gated" == "0" || "$start_gated" == "1" ]] || {
    printf 'error: ZEPHYR_DUMP_GATED=1 requires ZEPHYR_START_GATED=1\n' >&2
    exit 2
}
[[ "$start_delay_ms" =~ ^[0-9]+$ ]] || {
    printf 'error: ZEPHYR_START_DELAY_MS must be a non-negative integer\n' >&2
    exit 2
}
[[ "$sample_count" =~ ^[1-9][0-9]*$ ]] || {
    printf 'error: ZEPHYR_SAMPLE_COUNT must be a positive integer\n' >&2
    exit 2
}
[[ "$atk_early_uart" == "0" || "$atk_early_uart" == "1" ]] || {
    printf 'error: ZEPHYR_ATK_EARLY_UART must be 0 or 1\n' >&2
    exit 2
}

mkdir -p "$out_dir"
overlay="${out_dir}/zephyr-periodic-memory.overlay"
if [[ "$memory_address_cells" == "1" ]]; then
    printf '/* Generated by build-zephyr-periodic.sh. */\n&sram0 {\n\treg = <%s %s>;\n};\n' \
        "$memory_base" "$memory_size" > "$overlay"
else
    printf '/* Generated by build-zephyr-periodic.sh. */\n&sram0 {\n\treg = <0x0 %s 0x0 %s>;\n};\n' \
        "$memory_base" "$memory_size" > "$overlay"
fi
overlay_files=("$overlay")
if [[ -n "$extra_overlay" ]]; then
    [[ -f "$extra_overlay" ]] || {
        printf 'error: Zephyr extra overlay does not exist: %s\n' "$extra_overlay" >&2
        exit 1
    }
    overlay_files+=("$(realpath "$extra_overlay")")
fi
overlay_list="$(IFS=";"; printf "%s" "${overlay_files[*]}")"

cmake_extra_args=()
if [[ -n "$extra_conf" ]]; then
    [[ -f "$extra_conf" ]] || {
        printf 'error: Zephyr extra config does not exist: %s\n' "$extra_conf" >&2
        exit 1
    }
    extra_conf="$(realpath "$extra_conf")"
    cmake_extra_args+=("-DEXTRA_CONF_FILE=$extra_conf")
fi

# Zephyr 4.4.2's standalone-checkout path omits this companion file when the
# source is not inside a west workspace.
mkdir -p "$build_dir/Kconfig"
printf 'set(kconfig_env_dirs)\n' > "$build_dir/Kconfig/kconfig_module_dirs.cmake"

ZEPHYR_BASE="$zephyr_base" cmake --fresh -S "$app_dir" -B "$build_dir" -G Ninja \
    -DPython3_EXECUTABLE="$task123_python" \
    -DBOARD="$zephyr_board" \
    -DBUILD_VERSION="$zephyr_source_revision" \
    -DUSER_CACHE_DIR="$build_dir/user-cache" \
    -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile \
    -DCROSS_COMPILE="$cross_prefix" \
    -DRT_START_GATED="$start_gated" \
    -DRT_DUMP_GATED="$dump_gated" \
    -DRT_DUMP_CHUNK_ROWS="$dump_chunk_rows" \
    -DRT_START_DELAY_MS="$start_delay_ms" \
    -DRT_SAMPLE_COUNT="$sample_count" \
    -DRT_ATK_EARLY_UART="$atk_early_uart" \
    -DDTC_OVERLAY_FILE="$overlay_list" \
    "${cmake_extra_args[@]}"
cmake --build "$build_dir" --clean-first

elf="${build_dir}/zephyr/zephyr.elf"
source_bin="${build_dir}/zephyr/zephyr.bin"
staged_elf="${out_dir}/zephyr-periodic.elf"
staged_bin="${out_dir}/zephyr-periodic.bin"
staged_dts="${out_dir}/zephyr-periodic.dts"
staged_dtb="${out_dir}/zephyr-periodic.dtb"
manifest="${out_dir}/zephyr-periodic.manifest"
for path in "$elf" "$source_bin" "$build_dir/zephyr/zephyr.dts"; do
    [[ -f "$path" ]] || { printf 'error: Zephyr build did not produce %s\n' "$path" >&2; exit 1; }
done

cp "$elf" "$staged_elf"
cp "$source_bin" "$staged_bin"
cp "$build_dir/zephyr/zephyr.dts" "$staged_dts"
dtc -I dts -O dtb -o "$staged_dtb" "$staged_dts"
if [[ -n "$extra_conf" ]]; then
    cp "$extra_conf" "$out_dir/zephyr-periodic-extra.conf"
fi
entry_point="$("${cross_prefix}readelf" -hW "$staged_elf" | awk '/Entry point address:/ {print $4}')"
linked_base="$("${cross_prefix}readelf" -lW "$staged_elf" | awk '$1 == "LOAD" {print $3; exit}')"
[[ -n "$entry_point" && -n "$linked_base" ]] || {
    printf 'error: failed to inspect Zephyr ELF layout\n' >&2
    exit 1
}
(( linked_base == memory_base )) || {
    printf 'error: Zephyr linked base %s does not match requested %s\n' "$linked_base" "$memory_base" >&2
    exit 1
}
grep -aF "PERIODIC LATENCY COMPLETE samples=%d" "$staged_bin" >/dev/null || {
    printf 'error: staged image does not contain the periodic completion marker\n' >&2
    exit 1
}

{
    printf 'entry_point=%s\n' "$entry_point"
    printf 'linked_base=%s\n' "$linked_base"
    printf 'zephyr_commit=%s\n' "$zephyr_source_revision"
    printf 'source_commit=%s\n' "$(git -C "$repo_root" rev-parse HEAD)"
    printf 'board=%s\n' "$zephyr_board"
    printf 'memory_address_cells=%s\n' "$memory_address_cells"
    printf 'sample_count=%s\n' "$sample_count"
    printf 'start_gated=%s\n' "$start_gated"
    printf 'dump_gated=%s\n' "$dump_gated"
    printf 'dump_chunk_rows=%s\n' "$dump_chunk_rows"
    printf 'start_delay_ms=%s\n' "$start_delay_ms"
    printf 'atk_early_uart=%s\n' "$atk_early_uart"
    printf 'extra_overlay=%s\n' "${extra_overlay:-none}"
    if [[ -n "$extra_overlay" ]]; then
        printf 'extra_overlay_sha256=%s\n' "$(sha256sum "$extra_overlay" | awk '{print $1}')"
    fi
    printf 'extra_conf=%s\n' "${extra_conf:-none}"
    if [[ -n "$extra_conf" ]]; then
        printf 'extra_conf_sha256=%s\n' "$(sha256sum "$extra_conf" | awk '{print $1}')"
    fi
    printf 'toolchain=%s\n' "$("${cross_prefix}gcc" -dumpfullversion)"
    printf 'sha256=%s\n' "$(sha256sum "$staged_bin" | awk '{print $1}')"
} > "$manifest"

printf 'zephyr_periodic=%s entry=%s sha256=%s\n' \
    "$staged_bin" "$entry_point" "$(sha256sum "$staged_bin" | awk '{print $1}')"
